# Generated by Django 2.2.7 on 2019-11-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(default=0)),
                ('tracking_number', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('updated_time', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
            ],
        ),
    ]
